# Generated by Django 6.0.5 on 2026-05-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Загальна', max_length=100, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Нагадування'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Текст нотатки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
    ]
